fix: install should reject unknown scripts

diff --git a/bin/core/qol b/bin/core/qol
--- a/bin/core/qol
+++ b/bin/core/qol
@@ -21,6 +21,11 @@ if [ "$1" == "install" ]; then
     exit 1
     fi
 
+    if [ ! -e "$QOL_SCRIPTS_PATH/src/$2" ]; then
+        echo "Error: Source script $2 does not exist. Run \`qol list\` to see all available installations."
+        exit 1
+    fi
+
     ln -s $QOL_SCRIPTS_PATH/src/$2 $QOL_SCRIPTS_PATH/bin/$2
     if [ "$?" -eq 0 ]; then
         echo "$2 successfully installed"
