fix: error out when folder does not exist

diff --git a/src/folder-info b/src/folder-info
--- a/src/folder-info
+++ b/src/folder-info
@@ -30,6 +30,32 @@ SHOW_GIT=true
 FOLDER="$PWD"
 FOLDER_ARG_SET=false
 
+# Color definitions for Kitty terminal
+BOLD="\033[1m"
+DIM="\033[2m"
+RESET="\033[0m"
+
+# Kitty 256 colors
+CYAN="\033[38;5;6m"
+BLUE="\033[38;5;4m"
+GREEN="\033[38;5;2m"
+YELLOW="\033[38;5;3m"
+MAGENTA="\033[38;5;5m"
+WHITE="\033[38;5;15m"
+GRAY="\033[38;5;8m"
+RED="\033[38;5;1m"
+
+print_usage() {
+    echo "Usage:  folder-info [OPTIONS] FOLDER (FOLDER defaults to PWD)"
+    echo -e "    --no-details \t\t Skip details "
+    echo -e "    --no-file-breakdown \t Skip filetype breakdown "
+    echo -e "    --no-largest-files \t\t Skip listing largest files" 
+    echo -e "    --no-size \t\t\t Skip showing total size "
+    echo -e "    --no-counts \t\t Skip showing file, folder, and symlink counts."
+    echo -e "    --no-git \t\t\t Skip showing git information."
+    echo ""
+}
+
 # Parse arguments
 while [[ $# -gt 0 ]]; do
     case $1 in
@@ -58,13 +84,7 @@ while [[ $# -gt 0 ]]; do
             shift
             ;;
         --help)
-            echo "Usage:  folder-info [OPTIONS] FOLDER (FOLDER defaults to PWD)"
-            echo -e "    --no-details \t\t Skip details "
-            echo -e "    --no-file-breakdown \t Skip filetype breakdown "
-            echo -e "    --no-largest-files \t\t Skip listing largest files" 
-            echo -e "    --no-size \t\t\t Skip showing total size "
-            echo -e "    --no-counts \t\t Skip showing file, folder, and symlink counts."
-            echo -e "    --no-git \t\t\t Skip showing git information."
+            print_usage
             exit 0
             shift
             ;;
@@ -83,20 +103,13 @@ while [[ $# -gt 0 ]]; do
     esac
 done
 
-# Color definitions for Kitty terminal
-BOLD="\033[1m"
-DIM="\033[2m"
-RESET="\033[0m"
-
-# Kitty 256 colors
-CYAN="\033[38;5;6m"
-BLUE="\033[38;5;4m"
-GREEN="\033[38;5;2m"
-YELLOW="\033[38;5;3m"
-MAGENTA="\033[38;5;5m"
-WHITE="\033[38;5;15m"
-GRAY="\033[38;5;8m"
-RED="\033[38;5;1m"
+if [[ ! -d "$FOLDER" ]]; then
+    echo ""
+    echo -e "${RED}Error: folder not found.${RESET} $FOLDER"
+    echo ""
+    print_usage
+    exit 1
+fi
 
 # Helper function for section headers
 section_header() {
